name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  wake-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        # Updated path to the requirements file
        run: pip install -r .github/scripts/script_requirements.txt
          
      - name: Run Selenium script to wake app
        # Updated path to the python script
        run: python .github/scripts/wake_app.py